### ISSUE TITLE
Image size is shrinked to half of the original image

### ISSUE THREAD

**Issue by trglairnarra** [JimmyDaddy/react-native-image-marker#42] opened 2019-06-25 07:14 UTC
Having a picture with a size of 1701 x 2268 becomes 851 x 1134 after watermarked..

**Steps to reproduce the behavior:**
1. Process an image with the `markText` method with the following settings
```
{
    src: image,
    text: moment(new Date()).format('DD/MM/YYYY hh:mm A'),
    position: 'bottomRight',
    color: '#FFFF00',
    fontName: 'Arial',
    fontSize: 80,
    scale: 1,
    quality: 80,
}
```

**Expected behavior**
Size should still be the same with the size of the image that is supplied.

**Devlopment environment:**
 - react-native: 0.59.9
 - react-native-image-marker :  0.4.0 and up

**Smartphone:**
 - Device: Nexus 5X API 28 (Simulator)

In order to temporary patch the issue on my end. I am applying a scale of 2 on the `markText` in order to return to original size.

**Comment by JimmyDaddy** [comment] 2019-06-25 10:14
@trglairnarra I tested this problem this afternoon, I can't reproduce this problem. 
There is the test result：
![F6E0D291-0922-43C3-BABE-F6813A3E5F0F](https://user-images.githubusercontent.com/16460813/60089501-3358c680-9773-11e9-8d24-488018ae6074.jpg)

![5E15C86E-8F04-4F8D-8081-3925585DE271](https://user-images.githubusercontent.com/16460813/60090178-9f87fa00-9774-11e9-98b3-e7b68cedd240.jpg)

the image size didn't change.

**Comment by trglairnarra** [comment] 2019-06-26 02:44
whoa... maybe i'll try to test it more on other device.. closing this for now. thank you :)

**Comment by trglairnarra** [comment] 2019-06-27 09:22
i tested providing different images which follows:
- 1701 x 2268
- 1512 x 2016
- 1323 x 1764
- 1134 x 1512
- 960 x 1280

all of them are producing the same sizes, the same on the input. but for the 1701 x 2268 image size, it is the only one that is producing half of the size..

**Comment by JimmyDaddy** [comment] 2019-06-27 10:08
That's very STRANGE, I'll test this again while I'm spare.

**Comment by trglairnarra** [comment] 2019-06-28 03:16
In addition, the issue is only occurring on versions 0.4.0 and up. Been using it on past versions and its working fine, but since I need to upgrade to Android API 28 for the 64bit compliance I also upgraded it to version 0.4.0. Maybe it is related with the API 28 upgrade of the library?

**Comment by summer88123** [comment] 2019-09-26 02:40
@trglairnarra try this #49 
Fresco default config maxBitmapSize value is 2048. If your image width or height bigger then it, Fresco will make a SampleSize when decode image.

**Comment by JimmyDaddy** [comment] 2019-10-09 09:54
fixed on [v0.6.0](https://www.npmjs.com/package/react-native-image-marker), but you need to upgrade your RN to v0.60.0+ because of [fresco version](https://github.com/facebook/react-native/blob/8cf9505bd27c5dade33b17cc177fa5ef1613dbcd/ReactAndroid/gradle.properties#L15)

**Closed by JimmyDaddy** 2019-10-09 09:54 UTC

**Comment by yestay90** [comment] 2020-07-31 21:47
Hello, I have problem with image size. It is half of original size when adding icon to the image.

**Comment by EricLewe** [comment] 2020-11-26 00:02
@yestay90 can you validate if #73 addresses your issue?
